# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UiPathPack@3
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\project.jason'
    orchestratorConnection: 'AzureDevOps'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathTest@3
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'AzureDevOps'
    folderName: 'Shared'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'